import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "hi" | "pa";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About",
    "nav.gallery": "Gallery",
    "nav.contact": "Contact Us",
    "nav.donate": "Donate",
    "nav.urgent": "URGENT: Blood Request",
    "nav.register": "Register as Donor",
    "nav.requestBlood": "Request Blood/SDP",
    
    // Hero
    "hero.connecting": "Connecting Saviours.",
    "hero.delivering": "Delivering Hope.",
    "hero.subtitle": "Join India's most trusted blood donation network.",
    "hero.subtitle2": "Every donation saves up to 3 lives.",
    "hero.requestUrgent": "Request Blood Urgently",
    "hero.becomeDonor": "Become a Donor",
    "hero.unitsLabel": "Units Donated",
    "hero.donorsLabel": "Active Donors",
    "hero.livesLabel": "Lives Saved",
    "hero.supportLabel": "Support",
    "hero.badge": "24/7 Emergency Response Active",
    
    // Forms
    "form.bloodType": "Blood Type Required",
    "form.units": "Units Required",
    "form.patientName": "Patient Name",
    "form.hospitalName": "Hospital Name",
    "form.contactNumber": "Contact Number",
    "form.state": "State",
    "form.city": "City",
    "form.selectBloodType": "Select blood type",
    "form.selectState": "Select state",
    "form.selectCity": "Select city",
    "form.selectStateFirst": "Select state first",
    "form.submit": "Submit Emergency Request",
    "form.responseTime": "Our team responds within 15 minutes • Available 24/7",
    "form.fullName": "Full Name",
    "form.email": "Email",
    "form.phone": "Phone Number",
    "form.dob": "Date of Birth",
    "form.address": "Street Address",
    "form.pincode": "Pincode",
    "form.registerDonor": "Register as Donor",
    "form.personalInfo": "Personal Information",
    "form.addressInfo": "Address",
    
    // Titles
    "title.emergencyRequest": "Emergency Blood/SDP Request",
    "title.emergencyDesc": "Submit your urgent request and we'll connect you with donors immediately",
    "title.becomeDonor": "Become a Blood Donor",
    "title.becomeDonorDesc": "Join our community of life-savers and make a difference",
    
    // Impact Stats
    "impact.title": "Our Impact Dashboard",
    "impact.subtitle": "Real-time metrics of lives we're touching together",
    "impact.bloodUnits": "Blood Units Collected",
    "impact.plateletDonations": "Platelet Donations",
    "impact.activeDonors": "Active Donors",
    "impact.livesSaved": "Lives Saved",
    "impact.bloodDonation": "Blood Donation",
    "impact.bloodDonationDesc": "One blood donation can save up to 3 lives. Join our community of heroes today.",
    "impact.activeRequests": "Active Requests",
    "impact.plateletDonation": "Platelet (SDP) Donation",
    "impact.plateletDesc": "Critical for cancer patients and surgical cases. Your platelets can make miracles happen.",
    
    // About Page
    "about.title": "About Aashayein",
    "about.subtitle": "The Life Saviours - Connecting donors with those in need, one drop at a time",
    "about.mission": "Our Mission",
    "about.missionDesc1": "Aashayein is dedicated to saving lives by connecting blood donors with patients in need. We believe that every drop of blood donated is a gift of life, and our mission is to make this life-saving process as seamless and efficient as possible.",
    "about.missionDesc2": "Through our innovative platform, we bridge the gap between willing donors and urgent medical needs, ensuring that no patient has to wait when time is critical. We are committed to building a community of compassionate individuals who understand the value of giving blood.",
    "about.communityFirst": "Community First",
    "about.communityDesc": "Building a strong network of donors and recipients united by compassion",
    "about.quickResponse": "Quick Response",
    "about.quickResponseDesc": "Ensuring rapid connection between donors and patients in emergency situations",
    "about.excellence": "Excellence",
    "about.excellenceDesc": "Maintaining the highest standards in blood donation coordination and support",
    "about.whatWeDo": "What We Do",
    "about.tracking": "Real-Time Donor Tracking",
    "about.trackingDesc": "Our live tracker helps patients find available donors near them instantly, reducing wait times in critical situations.",
    "about.emergency": "Emergency Blood Requests",
    "about.emergencyDesc": "24/7 emergency request system that connects urgent needs with willing donors within minutes.",
    "about.management": "Donor Management",
    "about.managementDesc": "Comprehensive dashboard for donors to track their donation history, schedule appointments, and see their life-saving impact.",
    "about.ai": "AI-Powered Assistance",
    "about.aiDesc": "Smart assistant to answer questions about blood donation, eligibility, and help guide users through the process.",
    
    // Donate Page
    "donate.title": "Support Our Mission",
    "donate.subtitle": "Your donation helps us save lives and organize blood donation camps",
    "donate.makeADonation": "Make a Donation",
    "donate.bankTransfer": "Bank Transfer",
    "donate.accountName": "Account Name: Aashayein Foundation",
    "donate.accountNumber": "Account Number: XXXX XXXX XXXX",
    "donate.ifscCode": "IFSC Code: XXXXX0000",
    "donate.upiPayment": "UPI Payment",
    "donate.upiId": "UPI ID: aashayein@upi",
    "donate.donateNow": "Donate Now",
    
    // Gallery Page
    "gallery.title": "Gallery",
    "gallery.subtitle": "Moments of compassion and life-saving actions",
    "gallery.testimonials": "Stories That Inspire",
    "gallery.testimonialsDesc": "Hear from donors and recipients who have experienced the impact of blood donation",
    "gallery.bloodDonationCamp": "Blood Donation Camp 2025",
    "gallery.campDesc": "Community blood donation drive",
    "gallery.happyDonors": "Happy Donors",
    "gallery.donorsDesc": "Our valued donors making a difference",
    "gallery.medicalTeam": "Medical Team",
    "gallery.teamDesc": "Professional healthcare support",
    "gallery.bloodCollection": "Blood Collection",
    "gallery.collectionDesc": "Safe and hygienic collection process",
    "gallery.donorAppreciation": "Donor Appreciation",
    "gallery.appreciationDesc": "Celebrating our life-savers",
    "gallery.communityEvent": "Community Event",
    "gallery.eventDesc": "Bringing people together for a cause",
    
    // Footer
    "footer.brand": "Aashayein",
    "footer.tagline": "The Life Saviours",
    "footer.description": "Connecting blood and platelet donors with those in need. Together, we're saving lives every day.",
    "footer.quickLinks": "Quick Links",
    "footer.home": "Home",
    "footer.dashboard": "Dashboard",
    "footer.aboutUs": "About Us",
    "footer.gallery": "Gallery",
    "footer.services": "Services",
    "footer.requestBlood": "Request Blood/SDP",
    "footer.registerDonor": "Register as Donor",
    "footer.findBloodBanks": "Find Blood Banks",
    "footer.emergencySupport": "Emergency Support",
    "footer.contactUs": "Contact Us",
    "footer.helpline": "24/7 Helpline",
    "footer.email": "Email",
    "footer.address": "Address",
    "footer.location": "Jaipur, Rajasthan, India",
    "footer.copyright": "Aashayein: The Life Saviours. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.cookies": "Cookie Policy",
    
    // Donor Dashboard
    "dashboard.title": "Donor Dashboard",
    "dashboard.subtitle": "Track your donation journey and impact",
    "dashboard.totalDonations": "Total Donations",
    "dashboard.livesImpacted": "Lives impacted:",
    "dashboard.bloodType": "Blood Type",
    "dashboard.universalDonor": "Universal Donor",
    "dashboard.lastDonation": "Last Donation",
    "dashboard.monthsAgo": "months ago",
    "dashboard.achievement": "Achievement",
    "dashboard.gold": "Gold",
    "dashboard.donationsPlus": "donations",
    "dashboard.history": "Donation History",
    "dashboard.historyDesc": "Your complete donation record",
    "dashboard.exportPDF": "Export PDF",
    "dashboard.exportCSV": "Export CSV",
    "dashboard.wholeBlood": "Whole Blood",
    "dashboard.platelets": "Platelets",
    "dashboard.completed": "Completed",
    "dashboard.pdfSuccess": "PDF exported successfully!",
    "dashboard.csvSuccess": "CSV exported successfully!",
    
    // Live Tracker
    "tracker.title": "Live Blood Donor Tracker",
    "tracker.subtitle": "Find available blood donors near you in real-time",
    "tracker.available": "Available",
    "tracker.unavailable": "Unavailable",
    "tracker.away": "away",
    "tracker.contactDonor": "Contact Donor",
    "tracker.verified": "Verified",
    
    // Myths & Facts
    "myths.title": "Blood Donation Myths vs. Facts",
    "myths.subtitle": "Let's clear the misconceptions",
    "myths.progress": "Myths Explored",
    "myths.cta": "Still have questions?",
    "myths.ctaDesc": "Our team is here to help",
    "myths.contact": "Contact Us",
  },
  hi: {
    // Navigation
    "nav.home": "होम",
    "nav.about": "हमारे बारे में",
    "nav.gallery": "गैलरी",
    "nav.contact": "संपर्क करें",
    "nav.donate": "दान करें",
    "nav.urgent": "तत्काल: रक्त अनुरोध",
    "nav.register": "दाता के रूप में पंजीकरण करें",
    "nav.requestBlood": "रक्त/SDP का अनुरोध करें",
    
    // Hero
    "hero.connecting": "जीवनदाताओं को जोड़ना।",
    "hero.delivering": "आशा प्रदान करना।",
    "hero.subtitle": "भारत के सबसे विश्वसनीय रक्तदान नेटवर्क में शामिल हों।",
    "hero.subtitle2": "प्रत्येक दान 3 जीवन तक बचाता है।",
    "hero.requestUrgent": "तुरंत रक्त का अनुरोध करें",
    "hero.becomeDonor": "दाता बनें",
    "hero.unitsLabel": "दान की गई इकाइयाँ",
    "hero.donorsLabel": "सक्रिय दाता",
    "hero.livesLabel": "बचाई गई जिंदगियां",
    "hero.supportLabel": "सहायता",
    "hero.badge": "24/7 आपातकालीन प्रतिक्रिया सक्रिय",
    
    // Forms
    "form.bloodType": "आवश्यक रक्त समूह",
    "form.units": "आवश्यक इकाइयाँ",
    "form.patientName": "रोगी का नाम",
    "form.hospitalName": "अस्पताल का नाम",
    "form.contactNumber": "संपर्क नंबर",
    "form.state": "राज्य",
    "form.city": "शहर",
    "form.selectBloodType": "रक्त समूह चुनें",
    "form.selectState": "राज्य चुनें",
    "form.selectCity": "शहर चुनें",
    "form.selectStateFirst": "पहले राज्य चुनें",
    "form.submit": "आपातकालीन अनुरोध सबमिट करें",
    "form.responseTime": "हमारी टीम 15 मिनट में जवाब देती है • 24/7 उपलब्ध",
    "form.fullName": "पूरा नाम",
    "form.email": "ईमेल",
    "form.phone": "फोन नंबर",
    "form.dob": "जन्म तिथि",
    "form.address": "पता",
    "form.pincode": "पिनकोड",
    "form.registerDonor": "दाता के रूप में पंजीकरण करें",
    "form.personalInfo": "व्यक्तिगत जानकारी",
    "form.addressInfo": "पता",
    
    // Titles
    "title.emergencyRequest": "आपातकालीन रक्त/SDP अनुरोध",
    "title.emergencyDesc": "अपना तत्काल अनुरोध सबमिट करें और हम आपको तुरंत दाताओं से जोड़ेंगे",
    "title.becomeDonor": "रक्तदाता बनें",
    "title.becomeDonorDesc": "जीवन बचाने वालों के हमारे समुदाय में शामिल हों और बदलाव लाएं",
    
    // Impact Stats
    "impact.title": "हमारा प्रभाव डैशबोर्ड",
    "impact.subtitle": "जीवन को छूने वाले वास्तविक समय के मेट्रिक्स",
    "impact.bloodUnits": "एकत्रित रक्त इकाइयाँ",
    "impact.plateletDonations": "प्लेटलेट दान",
    "impact.activeDonors": "सक्रिय दाता",
    "impact.livesSaved": "बचाई गई जिंदगियां",
    "impact.bloodDonation": "रक्तदान",
    "impact.bloodDonationDesc": "एक रक्तदान 3 जीवन तक बचा सकता है। आज हमारे नायकों के समुदाय में शामिल हों।",
    "impact.activeRequests": "सक्रिय अनुरोध",
    "impact.plateletDonation": "प्लेटलेट (SDP) दान",
    "impact.plateletDesc": "कैंसर रोगियों और सर्जिकल मामलों के लिए महत्वपूर्ण। आपकी प्लेटलेट चमत्कार कर सकती हैं।",
    
    // About Page
    "about.title": "आशायें के बारे में",
    "about.subtitle": "जीवन रक्षक - दाताओं को जरूरतमंदों से जोड़ना, एक बूंद एक समय में",
    "about.mission": "हमारा मिशन",
    "about.missionDesc1": "आशायें रक्तदाताओं को जरूरतमंद रोगियों से जोड़कर जीवन बचाने के लिए समर्पित है। हम मानते हैं कि दान किया गया रक्त की हर बूंद जीवन का उपहार है, और हमारा मिशन इस जीवन रक्षक प्रक्रिया को यथासंभव सहज और कुशल बनाना है।",
    "about.missionDesc2": "अपने अभिनव मंच के माध्यम से, हम इच्छुक दाताओं और तत्काल चिकित्सा आवश्यकताओं के बीच की खाई को पाटते हैं, यह सुनिश्चित करते हुए कि जब समय महत्वपूर्ण है तो किसी भी रोगी को इंतजार नहीं करना पड़े। हम करुणामय व्यक्तियों का एक समुदाय बनाने के लिए प्रतिबद्ध हैं जो रक्तदान के मूल्य को समझते हैं।",
    "about.communityFirst": "समुदाय पहले",
    "about.communityDesc": "करुणा से एकजुट दाताओं और प्राप्तकर्ताओं का एक मजबूत नेटवर्क बनाना",
    "about.quickResponse": "त्वरित प्रतिक्रिया",
    "about.quickResponseDesc": "आपात स्थितियों में दाताओं और रोगियों के बीच तेजी से संबंध सुनिश्चित करना",
    "about.excellence": "उत्कृष्टता",
    "about.excellenceDesc": "रक्तदान समन्वय और समर्थन में उच्चतम मानकों को बनाए रखना",
    "about.whatWeDo": "हम क्या करते हैं",
    "about.tracking": "वास्तविक समय दाता ट्रैकिंग",
    "about.trackingDesc": "हमारा लाइव ट्रैकर रोगियों को तुरंत अपने पास उपलब्ध दाताओं को खोजने में मदद करता है, महत्वपूर्ण स्थितियों में प्रतीक्षा समय को कम करता है।",
    "about.emergency": "आपातकालीन रक्त अनुरोध",
    "about.emergencyDesc": "24/7 आपातकालीन अनुरोध प्रणाली जो मिनटों के भीतर तत्काल जरूरतों को इच्छुक दाताओं से जोड़ती है।",
    "about.management": "दाता प्रबंधन",
    "about.managementDesc": "दाताओं के लिए व्यापक डैशबोर्ड अपने दान इतिहास को ट्रैक करने, अपॉइंटमेंट शेड्यूल करने और अपने जीवन बचाने वाले प्रभाव को देखने के लिए।",
    "about.ai": "AI-संचालित सहायता",
    "about.aiDesc": "रक्तदान, पात्रता के बारे में प्रश्नों के उत्तर देने और उपयोगकर्ताओं को प्रक्रिया के माध्यम से मार्गदर्शन करने के लिए स्मार्ट सहायक।",
    
    // Donate Page
    "donate.title": "हमारे मिशन का समर्थन करें",
    "donate.subtitle": "आपका दान हमें जीवन बचाने और रक्तदान शिविर आयोजित करने में मदद करता है",
    "donate.makeADonation": "दान करें",
    "donate.bankTransfer": "बैंक ट्रांसफर",
    "donate.accountName": "खाता नाम: आशायें फाउंडेशन",
    "donate.accountNumber": "खाता संख्या: XXXX XXXX XXXX",
    "donate.ifscCode": "IFSC कोड: XXXXX0000",
    "donate.upiPayment": "UPI भुगतान",
    "donate.upiId": "UPI ID: aashayein@upi",
    "donate.donateNow": "अभी दान करें",
    
    // Gallery Page
    "gallery.title": "गैलरी",
    "gallery.subtitle": "करुणा और जीवन बचाने वाली कार्रवाइयों के क्षण",
    "gallery.testimonials": "प्रेरणादायक कहानियां",
    "gallery.testimonialsDesc": "दाताओं और प्राप्तकर्ताओं से सुनें जिन्होंने रक्तदान के प्रभाव का अनुभव किया है",
    "gallery.bloodDonationCamp": "रक्तदान शिविर 2025",
    "gallery.campDesc": "सामुदायिक रक्तदान अभियान",
    "gallery.happyDonors": "खुश दाता",
    "gallery.donorsDesc": "हमारे मूल्यवान दाता बदलाव ला रहे हैं",
    "gallery.medicalTeam": "चिकित्सा टीम",
    "gallery.teamDesc": "पेशेवर स्वास्थ्य सेवा समर्थन",
    "gallery.bloodCollection": "रक्त संग्रह",
    "gallery.collectionDesc": "सुरक्षित और स्वच्छ संग्रह प्रक्रिया",
    "gallery.donorAppreciation": "दाता प्रशंसा",
    "gallery.appreciationDesc": "हमारे जीवन रक्षकों का जश्न मना रहे हैं",
    "gallery.communityEvent": "सामुदायिक कार्यक्रम",
    "gallery.eventDesc": "एक उद्देश्य के लिए लोगों को एक साथ लाना",
    
    // Footer
    "footer.brand": "आशायें",
    "footer.tagline": "जीवन रक्षक",
    "footer.description": "रक्त और प्लेटलेट दाताओं को जरूरतमंदों से जोड़ना। साथ मिलकर, हम हर दिन जीवन बचा रहे हैं।",
    "footer.quickLinks": "त्वरित लिंक",
    "footer.home": "होम",
    "footer.dashboard": "डैशबोर्ड",
    "footer.aboutUs": "हमारे बारे में",
    "footer.gallery": "गैलरी",
    "footer.services": "सेवाएं",
    "footer.requestBlood": "रक्त/SDP का अनुरोध करें",
    "footer.registerDonor": "दाता के रूप में पंजीकरण करें",
    "footer.findBloodBanks": "रक्त बैंक खोजें",
    "footer.emergencySupport": "आपातकालीन सहायता",
    "footer.contactUs": "संपर्क करें",
    "footer.helpline": "24/7 हेल्पलाइन",
    "footer.email": "ईमेल",
    "footer.address": "पता",
    "footer.location": "जयपुर, राजस्थान, भारत",
    "footer.copyright": "आशायें: जीवन रक्षक। सर्वाधिकार सुरक्षित।",
    "footer.privacy": "गोपनीयता नीति",
    "footer.terms": "सेवा की शर्तें",
    "footer.cookies": "कुकी नीति",
    
    // Donor Dashboard
    "dashboard.title": "दाता डैशबोर्ड",
    "dashboard.subtitle": "अपने दान की यात्रा और प्रभाव को ट्रैक करें",
    "dashboard.totalDonations": "कुल दान",
    "dashboard.livesImpacted": "प्रभावित जीवन:",
    "dashboard.bloodType": "रक्त समूह",
    "dashboard.universalDonor": "सार्वभौमिक दाता",
    "dashboard.lastDonation": "अंतिम दान",
    "dashboard.monthsAgo": "महीने पहले",
    "dashboard.achievement": "उपलब्धि",
    "dashboard.gold": "स्वर्ण",
    "dashboard.donationsPlus": "दान",
    "dashboard.history": "दान इतिहास",
    "dashboard.historyDesc": "आपका पूरा दान रिकॉर्ड",
    "dashboard.exportPDF": "PDF निर्यात करें",
    "dashboard.exportCSV": "CSV निर्यात करें",
    "dashboard.wholeBlood": "संपूर्ण रक्त",
    "dashboard.platelets": "प्लेटलेट",
    "dashboard.completed": "पूर्ण",
    "dashboard.pdfSuccess": "PDF सफलतापूर्वक निर्यात किया गया!",
    "dashboard.csvSuccess": "CSV सफलतापूर्वक निर्यात किया गया!",
    
    // Live Tracker
    "tracker.title": "लाइव रक्त दाता ट्रैकर",
    "tracker.subtitle": "अपने पास वास्तविक समय में उपलब्ध रक्त दाताओं को खोजें",
    "tracker.available": "उपलब्ध",
    "tracker.unavailable": "अनुपलब्ध",
    "tracker.away": "दूर",
    "tracker.contactDonor": "दाता से संपर्क करें",
    "tracker.verified": "सत्यापित",
    
    // Myths & Facts
    "myths.title": "रक्तदान मिथक बनाम तथ्य",
    "myths.subtitle": "आइए भ्रांतियों को दूर करें",
    "myths.progress": "खोजे गए मिथक",
    "myths.cta": "अभी भी प्रश्न हैं?",
    "myths.ctaDesc": "हमारी टीम मदद के लिए यहां है",
    "myths.contact": "संपर्क करें",
  },
  pa: {
    // Navigation
    "nav.home": "ਘਰ",
    "nav.about": "ਸਾਡੇ ਬਾਰੇ",
    "nav.gallery": "ਗੈਲਰੀ",
    "nav.contact": "ਸੰਪਰਕ ਕਰੋ",
    "nav.donate": "ਦਾਨ ਕਰੋ",
    "nav.urgent": "ਜ਼ਰੂਰੀ: ਖੂਨ ਦੀ ਬੇਨਤੀ",
    "nav.register": "ਦਾਨੀ ਵਜੋਂ ਰਜਿਸਟਰ ਕਰੋ",
    "nav.requestBlood": "ਖੂਨ/SDP ਦੀ ਬੇਨਤੀ ਕਰੋ",
    
    // Hero
    "hero.connecting": "ਜੀਵਨ ਬਚਾਉਣ ਵਾਲਿਆਂ ਨੂੰ ਜੋੜਨਾ।",
    "hero.delivering": "ਉਮੀਦ ਪ੍ਰਦਾਨ ਕਰਨਾ।",
    "hero.subtitle": "ਭਾਰਤ ਦੇ ਸਭ ਤੋਂ ਭਰੋਸੇਮੰਦ ਖੂਨ ਦਾਨ ਨੈੱਟਵਰਕ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ।",
    "hero.subtitle2": "ਹਰ ਦਾਨ 3 ਜੀਵਨ ਤੱਕ ਬਚਾਉਂਦਾ ਹੈ।",
    "hero.requestUrgent": "ਤੁਰੰਤ ਖੂਨ ਦੀ ਬੇਨਤੀ ਕਰੋ",
    "hero.becomeDonor": "ਦਾਨੀ ਬਣੋ",
    "hero.unitsLabel": "ਦਾਨ ਕੀਤੀਆਂ ਇਕਾਈਆਂ",
    "hero.donorsLabel": "ਸਰਗਰਮ ਦਾਨੀ",
    "hero.livesLabel": "ਬਚਾਈਆਂ ਜ਼ਿੰਦਗੀਆਂ",
    "hero.supportLabel": "ਸਹਾਇਤਾ",
    "hero.badge": "24/7 ਐਮਰਜੈਂਸੀ ਜਵਾਬ ਸਰਗਰਮ",
    
    // Forms
    "form.bloodType": "ਲੋੜੀਂਦਾ ਖੂਨ ਗਰੁੱਪ",
    "form.units": "ਲੋੜੀਂਦੀਆਂ ਇਕਾਈਆਂ",
    "form.patientName": "ਮਰੀਜ਼ ਦਾ ਨਾਮ",
    "form.hospitalName": "ਹਸਪਤਾਲ ਦਾ ਨਾਮ",
    "form.contactNumber": "ਸੰਪਰਕ ਨੰਬਰ",
    "form.state": "ਰਾਜ",
    "form.city": "ਸ਼ਹਿਰ",
    "form.selectBloodType": "ਖੂਨ ਗਰੁੱਪ ਚੁਣੋ",
    "form.selectState": "ਰਾਜ ਚੁਣੋ",
    "form.selectCity": "ਸ਼ਹਿਰ ਚੁਣੋ",
    "form.selectStateFirst": "ਪਹਿਲਾਂ ਰਾਜ ਚੁਣੋ",
    "form.submit": "ਐਮਰਜੈਂਸੀ ਬੇਨਤੀ ਜਮ੍ਹਾਂ ਕਰੋ",
    "form.responseTime": "ਸਾਡੀ ਟੀਮ 15 ਮਿੰਟਾਂ ਵਿੱਚ ਜਵਾਬ ਦਿੰਦੀ ਹੈ • 24/7 ਉਪਲਬਧ",
    "form.fullName": "ਪੂਰਾ ਨਾਮ",
    "form.email": "ਈਮੇਲ",
    "form.phone": "ਫ਼ੋਨ ਨੰਬਰ",
    "form.dob": "ਜਨਮ ਤਾਰੀਖ",
    "form.address": "ਪਤਾ",
    "form.pincode": "ਪਿਨਕੋਡ",
    "form.registerDonor": "ਦਾਨੀ ਵਜੋਂ ਰਜਿਸਟਰ ਕਰੋ",
    "form.personalInfo": "ਨਿੱਜੀ ਜਾਣਕਾਰੀ",
    "form.addressInfo": "ਪਤਾ",
    
    // Titles
    "title.emergencyRequest": "ਐਮਰਜੈਂਸੀ ਖੂਨ/SDP ਬੇਨਤੀ",
    "title.emergencyDesc": "ਆਪਣੀ ਤੁਰੰਤ ਬੇਨਤੀ ਜਮ੍ਹਾਂ ਕਰੋ ਅਤੇ ਅਸੀਂ ਤੁਹਾਨੂੰ ਤੁਰੰਤ ਦਾਨੀਆਂ ਨਾਲ ਜੋੜਾਂਗੇ",
    "title.becomeDonor": "ਖੂਨ ਦਾਨੀ ਬਣੋ",
    "title.becomeDonorDesc": "ਜੀਵਨ ਬਚਾਉਣ ਵਾਲਿਆਂ ਦੇ ਸਾਡੇ ਭਾਈਚਾਰੇ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ ਅਤੇ ਬਦਲਾਅ ਲਿਆਓ",
    
    // Impact Stats
    "impact.title": "ਸਾਡਾ ਪ੍ਰਭਾਵ ਡੈਸ਼ਬੋਰਡ",
    "impact.subtitle": "ਅਸੀਂ ਮਿਲ ਕੇ ਛੂਹ ਰਹੇ ਜੀਵਨ ਦੇ ਰੀਅਲ-ਟਾਈਮ ਮੈਟ੍ਰਿਕਸ",
    "impact.bloodUnits": "ਇਕੱਠੀਆਂ ਖੂਨ ਇਕਾਈਆਂ",
    "impact.plateletDonations": "ਪਲੇਟਲੇਟ ਦਾਨ",
    "impact.activeDonors": "ਸਰਗਰਮ ਦਾਨੀ",
    "impact.livesSaved": "ਬਚਾਈਆਂ ਜ਼ਿੰਦਗੀਆਂ",
    "impact.bloodDonation": "ਖੂਨ ਦਾਨ",
    "impact.bloodDonationDesc": "ਇੱਕ ਖੂਨ ਦਾਨ 3 ਜੀਵਨ ਤੱਕ ਬਚਾ ਸਕਦਾ ਹੈ। ਅੱਜ ਸਾਡੇ ਨਾਇਕਾਂ ਦੇ ਭਾਈਚਾਰੇ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ।",
    "impact.activeRequests": "ਸਰਗਰਮ ਬੇਨਤੀਆਂ",
    "impact.plateletDonation": "ਪਲੇਟਲੇਟ (SDP) ਦਾਨ",
    "impact.plateletDesc": "ਕੈਂਸਰ ਮਰੀਜ਼ਾਂ ਅਤੇ ਸਰਜੀਕਲ ਮਾਮਲਿਆਂ ਲਈ ਮਹੱਤਵਪੂਰਨ। ਤੁਹਾਡੀਆਂ ਪਲੇਟਲੇਟਾਂ ਚਮਤਕਾਰ ਕਰ ਸਕਦੀਆਂ ਹਨ।",
    
    // About Page
    "about.title": "ਆਸ਼ਾਯੇਂ ਬਾਰੇ",
    "about.subtitle": "ਜੀਵਨ ਬਚਾਉਣ ਵਾਲੇ - ਦਾਨੀਆਂ ਨੂੰ ਲੋੜਵੰਦਾਂ ਨਾਲ ਜੋੜਨਾ, ਇੱਕ ਬੂੰਦ ਇੱਕ ਵਾਰ",
    "about.mission": "ਸਾਡਾ ਮਿਸ਼ਨ",
    "about.missionDesc1": "ਆਸ਼ਾਯੇਂ ਖੂਨ ਦਾਨੀਆਂ ਨੂੰ ਲੋੜਵੰਦ ਮਰੀਜ਼ਾਂ ਨਾਲ ਜੋੜ ਕੇ ਜੀਵਨ ਬਚਾਉਣ ਲਈ ਸਮਰਪਿਤ ਹੈ। ਅਸੀਂ ਮੰਨਦੇ ਹਾਂ ਕਿ ਦਾਨ ਕੀਤੇ ਖੂਨ ਦੀ ਹਰ ਬੂੰਦ ਜੀਵਨ ਦਾ ਤੋਹਫ਼ਾ ਹੈ, ਅਤੇ ਸਾਡਾ ਮਿਸ਼ਨ ਇਸ ਜੀਵਨ ਬਚਾਉਣ ਵਾਲੀ ਪ੍ਰਕਿਰਿਆ ਨੂੰ ਜਿੰਨਾ ਸੰਭਵ ਹੋ ਸਕੇ ਆਸਾਨ ਅਤੇ ਕੁਸ਼ਲ ਬਣਾਉਣਾ ਹੈ।",
    "about.missionDesc2": "ਆਪਣੇ ਨਵੀਨਤਮ ਪਲੇਟਫਾਰਮ ਦੁਆਰਾ, ਅਸੀਂ ਇੱਛੁਕ ਦਾਨੀਆਂ ਅਤੇ ਤੁਰੰਤ ਡਾਕਟਰੀ ਲੋੜਾਂ ਵਿਚਕਾਰ ਪਾੜੇ ਨੂੰ ਪੂਰਾ ਕਰਦੇ ਹਾਂ, ਇਹ ਯਕੀਨੀ ਬਣਾਉਂਦੇ ਹੋਏ ਕਿ ਜਦੋਂ ਸਮਾਂ ਮਹੱਤਵਪੂਰਨ ਹੈ ਤਾਂ ਕਿਸੇ ਵੀ ਮਰੀਜ਼ ਨੂੰ ਉਡੀਕ ਨਹੀਂ ਕਰਨੀ ਪੈਂਦੀ। ਅਸੀਂ ਦਇਆਵਾਨ ਵਿਅਕਤੀਆਂ ਦਾ ਇੱਕ ਭਾਈਚਾਰਾ ਬਣਾਉਣ ਲਈ ਵਚਨਬੱਧ ਹਾਂ ਜੋ ਖੂਨ ਦਾਨ ਦੇ ਮੁੱਲ ਨੂੰ ਸਮਝਦੇ ਹਨ।",
    "about.communityFirst": "ਭਾਈਚਾਰਾ ਪਹਿਲਾਂ",
    "about.communityDesc": "ਦਇਆ ਨਾਲ ਇਕਜੁੱਟ ਦਾਨੀਆਂ ਅਤੇ ਪ੍ਰਾਪਤਕਰਤਾਵਾਂ ਦਾ ਇੱਕ ਮਜ਼ਬੂਤ ਨੈੱਟਵਰਕ ਬਣਾਉਣਾ",
    "about.quickResponse": "ਤੁਰੰਤ ਜਵਾਬ",
    "about.quickResponseDesc": "ਐਮਰਜੈਂਸੀ ਸਥਿਤੀਆਂ ਵਿੱਚ ਦਾਨੀਆਂ ਅਤੇ ਮਰੀਜ਼ਾਂ ਵਿਚਕਾਰ ਤੇਜ਼ ਸੰਪਰਕ ਯਕੀਨੀ ਬਣਾਉਣਾ",
    "about.excellence": "ਉੱਤਮਤਾ",
    "about.excellenceDesc": "ਖੂਨ ਦਾਨ ਤਾਲਮੇਲ ਅਤੇ ਸਹਾਇਤਾ ਵਿੱਚ ਉੱਚਤਮ ਮਿਆਰਾਂ ਨੂੰ ਬਣਾਈ ਰੱਖਣਾ",
    "about.whatWeDo": "ਅਸੀਂ ਕੀ ਕਰਦੇ ਹਾਂ",
    "about.tracking": "ਰੀਅਲ-ਟਾਈਮ ਦਾਨੀ ਟਰੈਕਿੰਗ",
    "about.trackingDesc": "ਸਾਡਾ ਲਾਈਵ ਟਰੈਕਰ ਮਰੀਜ਼ਾਂ ਨੂੰ ਤੁਰੰਤ ਆਪਣੇ ਨੇੜੇ ਉਪਲਬਧ ਦਾਨੀਆਂ ਨੂੰ ਲੱਭਣ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ, ਮਹੱਤਵਪੂਰਨ ਸਥਿਤੀਆਂ ਵਿੱਚ ਉਡੀਕ ਦੇ ਸਮੇਂ ਨੂੰ ਘਟਾਉਂਦਾ ਹੈ।",
    "about.emergency": "ਐਮਰਜੈਂਸੀ ਖੂਨ ਬੇਨਤੀਆਂ",
    "about.emergencyDesc": "24/7 ਐਮਰਜੈਂਸੀ ਬੇਨਤੀ ਪ੍ਰਣਾਲੀ ਜੋ ਮਿੰਟਾਂ ਵਿੱਚ ਤੁਰੰਤ ਲੋੜਾਂ ਨੂੰ ਇੱਛੁਕ ਦਾਨੀਆਂ ਨਾਲ ਜੋੜਦੀ ਹੈ।",
    "about.management": "ਦਾਨੀ ਪ੍ਰਬੰਧਨ",
    "about.managementDesc": "ਦਾਨੀਆਂ ਲਈ ਵਿਆਪਕ ਡੈਸ਼ਬੋਰਡ ਆਪਣੇ ਦਾਨ ਇਤਿਹਾਸ ਨੂੰ ਟਰੈਕ ਕਰਨ, ਮੁਲਾਕਾਤਾਂ ਸ਼ੈਡਿਊਲ ਕਰਨ, ਅਤੇ ਆਪਣੇ ਜੀਵਨ ਬਚਾਉਣ ਵਾਲੇ ਪ੍ਰਭਾਵ ਨੂੰ ਦੇਖਣ ਲਈ।",
    "about.ai": "AI-ਸੰਚਾਲਿਤ ਸਹਾਇਤਾ",
    "about.aiDesc": "ਖੂਨ ਦਾਨ, ਯੋਗਤਾ ਬਾਰੇ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਦੇਣ ਅਤੇ ਉਪਭੋਗਤਾਵਾਂ ਨੂੰ ਪ੍ਰਕਿਰਿਆ ਦੁਆਰਾ ਮਾਰਗਦਰਸ਼ਨ ਕਰਨ ਲਈ ਸਮਾਰਟ ਸਹਾਇਕ।",
    
    // Donate Page
    "donate.title": "ਸਾਡੇ ਮਿਸ਼ਨ ਦਾ ਸਮਰਥਨ ਕਰੋ",
    "donate.subtitle": "ਤੁਹਾਡਾ ਦਾਨ ਸਾਨੂੰ ਜੀਵਨ ਬਚਾਉਣ ਅਤੇ ਖੂਨ ਦਾਨ ਕੈਂਪਾਂ ਦਾ ਆਯੋਜਨ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ",
    "donate.makeADonation": "ਦਾਨ ਕਰੋ",
    "donate.bankTransfer": "ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ",
    "donate.accountName": "ਖਾਤਾ ਨਾਮ: ਆਸ਼ਾਯੇਂ ਫਾਊਂਡੇਸ਼ਨ",
    "donate.accountNumber": "ਖਾਤਾ ਨੰਬਰ: XXXX XXXX XXXX",
    "donate.ifscCode": "IFSC ਕੋਡ: XXXXX0000",
    "donate.upiPayment": "UPI ਭੁਗਤਾਨ",
    "donate.upiId": "UPI ID: aashayein@upi",
    "donate.donateNow": "ਹੁਣੇ ਦਾਨ ਕਰੋ",
    
    // Gallery Page
    "gallery.title": "ਗੈਲਰੀ",
    "gallery.subtitle": "ਦਇਆ ਅਤੇ ਜੀਵਨ ਬਚਾਉਣ ਵਾਲੀਆਂ ਕਾਰਵਾਈਆਂ ਦੇ ਪਲ",
    "gallery.testimonials": "ਪ੍ਰੇਰਨਾਦਾਇਕ ਕਹਾਣੀਆਂ",
    "gallery.testimonialsDesc": "ਦਾਨੀਆਂ ਅਤੇ ਪ੍ਰਾਪਤਕਰਤਾਵਾਂ ਤੋਂ ਸੁਣੋ ਜਿਨ੍ਹਾਂ ਨੇ ਖੂਨ ਦਾਨ ਦੇ ਪ੍ਰਭਾਵ ਦਾ ਅਨੁਭਵ ਕੀਤਾ ਹੈ",
    "gallery.bloodDonationCamp": "ਖੂਨ ਦਾਨ ਕੈਂਪ 2025",
    "gallery.campDesc": "ਕਮਿਊਨਿਟੀ ਖੂਨ ਦਾਨ ਮੁਹਿੰਮ",
    "gallery.happyDonors": "ਖੁਸ਼ ਦਾਨੀ",
    "gallery.donorsDesc": "ਸਾਡੇ ਕੀਮਤੀ ਦਾਨੀ ਫਰਕ ਪਾ ਰਹੇ ਹਨ",
    "gallery.medicalTeam": "ਮੈਡੀਕਲ ਟੀਮ",
    "gallery.teamDesc": "ਪੇਸ਼ੇਵਰ ਸਿਹਤ ਸੇਵਾ ਸਹਾਇਤਾ",
    "gallery.bloodCollection": "ਖੂਨ ਇਕੱਠਾ ਕਰਨਾ",
    "gallery.collectionDesc": "ਸੁਰੱਖਿਅਤ ਅਤੇ ਸਾਫ਼-ਸੁਥਰੀ ਇਕੱਠੀ ਪ੍ਰਕਿਰਿਆ",
    "gallery.donorAppreciation": "ਦਾਨੀ ਪ੍ਰਸ਼ੰਸਾ",
    "gallery.appreciationDesc": "ਸਾਡੇ ਜੀਵਨ ਬਚਾਉਣ ਵਾਲਿਆਂ ਦਾ ਜਸ਼ਨ ਮਨਾ ਰਹੇ ਹਾਂ",
    "gallery.communityEvent": "ਕਮਿਊਨਿਟੀ ਸਮਾਗਮ",
    "gallery.eventDesc": "ਇੱਕ ਉਦੇਸ਼ ਲਈ ਲੋਕਾਂ ਨੂੰ ਇਕੱਠੇ ਲਿਆਉਣਾ",
    
    // Footer
    "footer.brand": "ਆਸ਼ਾਯੇਂ",
    "footer.tagline": "ਜੀਵਨ ਬਚਾਉਣ ਵਾਲੇ",
    "footer.description": "ਖੂਨ ਅਤੇ ਪਲੇਟਲੇਟ ਦਾਨੀਆਂ ਨੂੰ ਲੋੜਵੰਦਾਂ ਨਾਲ ਜੋੜਨਾ। ਇਕੱਠੇ, ਅਸੀਂ ਹਰ ਦਿਨ ਜੀਵਨ ਬਚਾ ਰਹੇ ਹਾਂ।",
    "footer.quickLinks": "ਤੁਰੰਤ ਲਿੰਕ",
    "footer.home": "ਘਰ",
    "footer.dashboard": "ਡੈਸ਼ਬੋਰਡ",
    "footer.aboutUs": "ਸਾਡੇ ਬਾਰੇ",
    "footer.gallery": "ਗੈਲਰੀ",
    "footer.services": "ਸੇਵਾਵਾਂ",
    "footer.requestBlood": "ਖੂਨ/SDP ਦੀ ਬੇਨਤੀ ਕਰੋ",
    "footer.registerDonor": "ਦਾਨੀ ਵਜੋਂ ਰਜਿਸਟਰ ਕਰੋ",
    "footer.findBloodBanks": "ਖੂਨ ਬੈਂਕ ਲੱਭੋ",
    "footer.emergencySupport": "ਐਮਰਜੈਂਸੀ ਸਹਾਇਤਾ",
    "footer.contactUs": "ਸੰਪਰਕ ਕਰੋ",
    "footer.helpline": "24/7 ਹੈਲਪਲਾਈਨ",
    "footer.email": "ਈਮੇਲ",
    "footer.address": "ਪਤਾ",
    "footer.location": "ਜੈਪੁਰ, ਰਾਜਸਥਾਨ, ਭਾਰਤ",
    "footer.copyright": "ਆਸ਼ਾਯੇਂ: ਜੀਵਨ ਬਚਾਉਣ ਵਾਲੇ। ਸਾਰੇ ਅਧਿਕਾਰ ਸੁਰੱਖਿਅਤ।",
    "footer.privacy": "ਗੋਪਨੀਯਤਾ ਨੀਤੀ",
    "footer.terms": "ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ",
    "footer.cookies": "ਕੁਕੀ ਨੀਤੀ",
    
    // Donor Dashboard
    "dashboard.title": "ਦਾਨੀ ਡੈਸ਼ਬੋਰਡ",
    "dashboard.subtitle": "ਆਪਣੀ ਦਾਨ ਯਾਤਰਾ ਅਤੇ ਪ੍ਰਭਾਵ ਨੂੰ ਟਰੈਕ ਕਰੋ",
    "dashboard.totalDonations": "ਕੁੱਲ ਦਾਨ",
    "dashboard.livesImpacted": "ਪ੍ਰਭਾਵਿਤ ਜੀਵਨ:",
    "dashboard.bloodType": "ਖੂਨ ਗਰੁੱਪ",
    "dashboard.universalDonor": "ਸਰਵ ਵਿਆਪਕ ਦਾਨੀ",
    "dashboard.lastDonation": "ਆਖਰੀ ਦਾਨ",
    "dashboard.monthsAgo": "ਮਹੀਨੇ ਪਹਿਲਾਂ",
    "dashboard.achievement": "ਪ੍ਰਾਪਤੀ",
    "dashboard.gold": "ਸੋਨਾ",
    "dashboard.donationsPlus": "ਦਾਨ",
    "dashboard.history": "ਦਾਨ ਇਤਿਹਾਸ",
    "dashboard.historyDesc": "ਤੁਹਾਡਾ ਪੂਰਾ ਦਾਨ ਰਿਕਾਰਡ",
    "dashboard.exportPDF": "PDF ਨਿਰਯਾਤ ਕਰੋ",
    "dashboard.exportCSV": "CSV ਨਿਰਯਾਤ ਕਰੋ",
    "dashboard.wholeBlood": "ਪੂਰਾ ਖੂਨ",
    "dashboard.platelets": "ਪਲੇਟਲੇਟਸ",
    "dashboard.completed": "ਪੂਰਾ",
    "dashboard.pdfSuccess": "PDF ਸਫਲਤਾਪੂਰਵਕ ਨਿਰਯਾਤ ਕੀਤਾ ਗਿਆ!",
    "dashboard.csvSuccess": "CSV ਸਫਲਤਾਪੂਰਵਕ ਨਿਰਯਾਤ ਕੀਤਾ ਗਿਆ!",
    
    // Live Tracker
    "tracker.title": "ਲਾਈਵ ਖੂਨ ਦਾਨੀ ਟਰੈਕਰ",
    "tracker.subtitle": "ਆਪਣੇ ਨੇੜੇ ਰੀਅਲ-ਟਾਈਮ ਵਿੱਚ ਉਪਲਬਧ ਖੂਨ ਦਾਨੀਆਂ ਨੂੰ ਲੱਭੋ",
    "tracker.available": "ਉਪਲਬਧ",
    "tracker.unavailable": "ਅਨੁਪਲਬਧ",
    "tracker.away": "ਦੂਰ",
    "tracker.contactDonor": "ਦਾਨੀ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
    "tracker.verified": "ਤਸਦੀਕ ਸ਼ੁਦਾ",
    
    // Myths & Facts
    "myths.title": "ਖੂਨ ਦਾਨ ਮਿੱਥ ਬਨਾਮ ਤੱਥ",
    "myths.subtitle": "ਆਓ ਗਲਤਫ਼ਹਿਮੀਆਂ ਨੂੰ ਦੂਰ ਕਰੀਏ",
    "myths.progress": "ਖੋਜੇ ਗਏ ਮਿੱਥ",
    "myths.cta": "ਅਜੇ ਵੀ ਸਵਾਲ ਹਨ?",
    "myths.ctaDesc": "ਸਾਡੀ ਟੀਮ ਮਦਦ ਲਈ ਇੱਥੇ ਹੈ",
    "myths.contact": "ਸੰਪਰਕ ਕਰੋ",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
